- hosts: all
  become: yes
  tasks:
    - name: Run some command
      shell: uname -a; df -h ;date
      register: OUT
 
    - name: Print OUT Variable
      debug:
        msg: "{{OUT.stdout_lines}}"
