- hosts:  all
  become: yes
  tasks:
    - name: Install Web Server
      package:
        name: httpd
        state: present

    - name: Start Web Server
      service:
        name: httpd
        state: started
        enabled: yes
